### PR TITLE
Fix/map portal orientation mode with sprite form not orient properly when using orientation mode top

### LINKED ISSUE #372: mapPortal orientation mode with sprite form
Bots with the form tag set to sprite do not orient properly when using orientationMode top.

https://www.loom.com/share/249b79b3b49d4317916d605dff0010bb?sid=f0158bdc-c481-473c-9a5e-72ca6294d96f

### PR DESCRIPTION
**Pull request by TroyceGowdy**
fixes #372

### CODE REVIEW

File: src/aux-server/aux-web/shared/scene/decorators/DimensionPositionDecorator.ts [hunk 1]
```diff
@@ -281,24 +281,89 @@ export class DimensionPositionDecorator extends AuxBot3DDecoratorBase {
...
+
+                    const invTransform = new Matrix4()
+                        .copy(coordinateTransform)
+                        .invert();
+                    const localDirection = globalDirection
+                        .clone()
+                        .applyMatrix4(invTransform);
+
+                    const adjustedGlobalDirection =
+                        localDirection.applyMatrix4(coordinateTransform);
```
Comment (KallynGowdy) [inline src/aux-server/aux-web/shared/scene/decorators/DimensionPositionDecorator.ts:327]: @TroyceGowdy All this is unnecessary. `globalDirection` is the same as `objWorld`. `adjustedGlobalDirection` is also the same as `objWorld`. `localDirection` is the same as `0,0,0`. `invTransform` isn't used for anything useful.

**Review by KallynGowdy — CHANGES_REQUESTED** [review]
Saw one thing. Everything else looks ok
