### PR TITLE
Fix/calculate viewport coordinates from position in map portal does not produce expected results

### LINKED ISSUE #571: os.calculateViewportCoordinatesFromPosition() in the mapPortal does not seem to produce expected results.
os.calculateViewportCoordinatesFromPosition() returns incorrect results that only seem to be affected by the angle the camera is at (not the position of the pointer on the screen/camera).

https://www.loom.com/share/4331da2b5593423a9656f298c8f8626f?sid=ee07dd98-ed62-461b-bd7e-2ef957f4b990

### PR DESCRIPTION
**Pull request by TroyceGowdy**
fixes #571

### CODE REVIEW

File: src/aux-server/aux-web/aux-player/scene/PlayerGame.ts [hunk 1]
```diff
@@ -1139,23 +1139,77 @@ export class PlayerGame extends Game {
...
+            portalTag = 'mapPortal';
+        } else if (e.portal === 'grid') {
+            portalTag = 'gridPortal';
+        } else if (e.portal === 'miniGrid') {
+            portalTag = 'miniGridPortal';
+        } else if (e.portal === 'miniMap') {
+            portalTag = 'miniMapPortal';
+        } else {
+            portalTag = getPortalTag(e.portal);
+        }
```
Comment (KallynGowdy) [inline src/aux-server/aux-web/aux-player/scene/PlayerGame.ts:1158]: @TroyceGowdy This change isn't needed. `getPortalTag()` does the job of getting the correct portal tag fine on its own.

File: src/aux-server/aux-web/aux-player/scene/PlayerGame.ts [hunk 2]
```diff
@@ -1139,23 +1139,77 @@ export class PlayerGame extends Game {
...
+                    vector.applyMatrix4(coordinateTransform);
+                } else {
+                    const lon = position.x * (Math.PI / 180);
+                    const lat = position.y * (Math.PI / 180);
+
+                    const x = EARTH_RADIUS * Math.cos(lat) * Math.cos(lon);
+                    const y = EARTH_RADIUS * Math.sin(lat);
+                    const z = EARTH_RADIUS * Math.cos(lat) * Math.sin(lon);
+
+                    vector = new Vector3(x, y, z);
```
Comment (KallynGowdy) [inline src/aux-server/aux-web/aux-player/scene/PlayerGame.ts:1191]: @TroyceGowdy Do you know if this code ever gets hit? I believe that coordinateTransform should always be truthy for the map portals, so this section of code presumably does nothing.

File: src/aux-server/aux-web/aux-player/scene/PlayerGame.ts [hunk 3]
```diff
@@ -1139,23 +1139,77 @@ export class PlayerGame extends Game {
...
+
+            const position = {
+                x: e.position.x,
+                y: e.position.y,
+                z: e.position.z,
+            };
+
+            let vector;
+
+            if (isMapPortal) {
```
Comment (KallynGowdy) [inline src/aux-server/aux-web/aux-player/scene/PlayerGame.ts:1176]: @TroyceGowdy Instead of checking for the map portal directly, please check for the presence of a coordinate transform instead.

File: src/aux-server/aux-web/aux-player/scene/PlayerGame.ts [hunk 4]
```diff
@@ -1139,23 +1139,77 @@ export class PlayerGame extends Game {
...
+                    position.z * gridScale
+                );
+
+                const coordinateTransform = _3dSim.coordinateTransformer
+                    ? _3dSim.coordinateTransformer(position)
+                    : null;
+
+                if (coordinateTransform) {
+                    vector.applyMatrix4(coordinateTransform);
+                }
```
Comment (KallynGowdy) [inline src/aux-server/aux-web/aux-player/scene/PlayerGame.ts:1206]: @TroyceGowdy This section of code isn't needed if you check for the coordinate transform above

File: src/aux-server/aux-web/aux-player/scene/PlayerGame.ts [hunk 5]
```diff
@@ -1139,23 +1139,77 @@ export class PlayerGame extends Game {
             sim.helper.transaction(asyncResult(e.taskId, null));
         }
     }
-
+    //MY CHANGES START HERE
```
Comment (KallynGowdy) [inline src/aux-server/aux-web/aux-player/scene/PlayerGame.ts:1142]: @TroyceGowdy Please remove this comment

**Review by KallynGowdy — CHANGES_REQUESTED** [review]
