### PR TITLE
Fix/show upload files dialog cuts off upload button

### LINKED ISSUE #347: The `os.showUploadFiles()` dialog cuts off the "Upload" button when a lot of files are added
The dialog should scroll once the number of files causes the dialog to reach its max height. Additionally, the "Upload" button should always be visible, no matter how many files are in the dialog.

Image

### PR DESCRIPTION
**Pull request by TroyceGowdy**
fixes #347

### CODE REVIEW

File: src/aux-server/aux-web/shared/vue-components/UploadServerModal/UploadServerModal.vue [hunk 1]
```diff
@@ -1,7 +1,7 @@
 <template>
     <md-dialog :md-active.sync="isOpen" class="bot-upload-dialog">
         <md-dialog-title>Upload Files</md-dialog-title>
-        <div class="bot-upload-container">
+        <div class="bot-upload-container" style="max-height: 400px; overflow-y: auto">
```
Comment (KallynGowdy) [inline src/aux-server/aux-web/shared/vue-components/UploadServerModal/UploadServerModal.vue:4]: @TroyceGowdy Can you place these styles in UploadServerModal.css and use the `.bot-upload-container` CSS class?

**Review by KallynGowdy — CHANGES_REQUESTED** [review]
